### ISSUE TITLE
Lights stuck in color

### ISSUE THREAD

**Issue by MaxdeMooij** [j4velin/HueNotifier#1]
In cases of receiving multiple push notifications of the same app, the lights won't change back to its original color state.

**Comment by j4velin** [comment]
Hey,
please try the debug version from here: http://j4velin.de/debug/ - it'll write some debug information to a logfile on your external memory (/sdcard/). Please send me this file after the issue occurs again.
Thanks,
Thomas

**Comment by MaxdeMooij** [comment]
Hey, I've attached the debug file. I think the error occurs on line 356 at 23:35:25. It does the revert state response twice for every lamp. In the second revert state response, the value is changed to 0.5170 in stead of the original 0.4066. 

`1 mei 2017 23:35:24 - revert state response: [{"success":{"/lights/2/state/on":true}}, {"success":{"/lights/2/state/xy":[0.4448,0.4066]}}]
1 mei 2017 23:35:24 - done 2
1 mei 2017 23:35:24 - revert state response: [{"success":{"/lights/1/state/on":true}}, {"success":{"/lights/1/state/xy":[0.4448,0.4066]}}]
1 mei 2017 23:35:24 - done 1
1 mei 2017 23:35:24 - revert state response: [{"success":{"/lights/3/state/on":true}}, {"success":{"/lights/3/state/xy":[0.4448,0.4066]}}]
1 mei 2017 23:35:24 - done 3
1 mei 2017 23:35:25 - revert state response: [{"success":{"/lights/3/state/on":true}}, {"success":{"/lights/3/state/xy":[0.4080,0.5170]}}]
1 mei 2017 23:35:25 - done 3
1 mei 2017 23:35:25 - revert state response: [{"success":{"/lights/1/state/on":true}}, {"success":{"/lights/1/state/xy":[0.4080,0.5170]}}]
1 mei 2017 23:35:25 - done 1
1 mei 2017 23:35:25 - revert state response: [{"success":{"/lights/2/state/on":true}}, {"success":{"/lights/2/state/xy":[0.4080,0.5170]}}]
1 mei 2017 23:35:25 - done 2
1 mei 2017 23:35:25 - received notification from com.whatsapp, people=null`

A second thing I noticed: it says the current state correctly at line 334. But at line 344, the current state is changed.

`1 mei 2017 23:35:22 - received notification from com.whatsapp, people=null
1 mei 2017 23:35:22 - doColorFlash for 1
1 mei 2017 23:35:22 - doColorFlash for 2
1 mei 2017 23:35:22 - doColorFlash for 3
1 mei 2017 23:35:22 - current state: name=Bed Lamp, state=on=true, x=0.4448, y=0.4066, modelid=LCT007
1 mei 2017 23:35:22 - current state: name=Staande Lamp, state=on=true, x=0.4448, y=0.4066, modelid=LCT007
1 mei 2017 23:35:22 - current state: name=Bureau Lamp, state=on=true, x=0.4448, y=0.4066, modelid=LCT007
1 mei 2017 23:35:22 - set alert state response: [{"success":{"/lights/2/state/on":true}}, {"success":{"/lights/2/state/xy":[0.4080,0.5170]}}]
1 mei 2017 23:35:23 - set alert state response: [{"success":{"/lights/1/state/on":true}}, {"success":{"/lights/1/state/xy":[0.4080,0.5170]}}]
1 mei 2017 23:35:23 - set alert state response: [{"success":{"/lights/3/state/on":true}}, {"success":{"/lights/3/state/xy":[0.4080,0.5170]}}]
1 mei 2017 23:35:24 - received notification from com.whatsapp, people=null
1 mei 2017 23:35:24 - doColorFlash for 1
1 mei 2017 23:35:24 - doColorFlash for 2
1 mei 2017 23:35:24 - doColorFlash for 3
1 mei 2017 23:35:24 - current state: name=Bureau Lamp, state=on=true, x=0.408, y=0.517, modelid=LCT007
1 mei 2017 23:35:24 - current state: name=Staande Lamp, state=on=true, x=0.408, y=0.517, modelid=LCT007
1 mei 2017 23:35:24 - current state: name=Bed Lamp, state=on=true, x=0.408, y=0.517, modelid=LCT007`

Maybe it's "received notification from com.whatsapp, people=null" that causes the problem.

Side info: I'm using whatsapp web (if that could be an issue).

Anyway, I wish I could help you solve the issue, but my app programming skills are not good. But if you need any help with design things, let me know!

Thanks for your time!
Max

[HueNotifier.txt](https://github.com/j4velin/HueNotifier/files/968904/HueNotifier.txt)

**Comment by j4velin** [comment]
Thanks for the log and sorry for the late reply. I updated the debug version https://j4velin.de/debug/HueNotifier-debug.apk - could you give it another try?

**Comment by MaxdeMooij** [comment]
I think the bug is fixed, it doesn't occur anymore! Thanks man!

**Comment by j4velin** [comment]
Thanks for testing!
